### ISSUE TITLE
No reports are generated if the maximum requests at ipinfo.io are exceeded

### ISSUE THREAD

**Issue by arminbl** [aaron555/fail2ban-analyse#1]
If there are many IP adresses in the logfile which have to be looked up, it happens that the maximum amount of allowed requests at ipinfo.io is reached. If that happens, no reports at all are created.

**Comment by aaron555** [comment]
Sorry it took so long!

This was due to the fact that a failure to achieve ipinfo.io lookup was considered an error, so although the reports were all created in the temp location the wrapper shell script exited.

I have now changed the logic so the failure to lookup is a warning instead of an error, and so still results in an exit 0 from the inner analysis process.  The wrapper will then attempt to continue, although of course the parts reliant on geo-location IP lookup will fail.
